lecture/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo_list/', include('todo_list.urls'))
]

todo_list/urls.py
from django.urls import path
from django.conf.urls import url
from .views import delete_item, index, details, create, delete_list, update_list, delete_item, add_item, mark_item, update_item
app_name='todo'
urlpatterns = [
    path('', index, name='index'),

    path('<int:list_id>/', details, name='list_details'),
    path('create/', create, name='list_create'),
    path('deleteL/<int:list_id>/', delete_list, name='list_delete'),
    path('updateL/<int:list_id2>/', update_list, name='list_update'),
    path('deleteI/<int:item_id>/', delete_item, name='item_delete'),
    path('addI/<int:list_id>/', add_item, name='item_add'),
    path('markI/<int:item_id>/', mark_item, name='item_mark'),
    path('updateI/<int:item_id>/', update_item, name='item_update')



]

todo_list/models.py
from django.db import models
# from datetime import datetime
from django.utils import timezone

# Create your models here.

class TodoList(models.Model):

    list_name = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.list_name}"


class TodoItem(models.Model):

    title = models.CharField(max_length=100)
    checked = models.BooleanField(default=False)
    due_date = models.DateTimeField(null=True)
    
    todo_list = models.ForeignKey(to=TodoList, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.todo_list.list_name}: {self.title}"

todo_list/forms.py
from django import forms
from django.forms import DateTimeInput
from .models import TodoItem, TodoList
class datetime(forms.DateTimeInput):
    input_type = 'datetime-local'
class Itemform(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['title', 'checked', 'due_date']
        exclude = ('todo_list',) 
        
        widgets = {'due_date': datetime()}

todo_list/views.py
from django.shortcuts import redirect, render
import datetime
from django.http import HttpResponse, Http404
from .models import TodoList, TodoItem
from django.template import loader
from django.urls import path
from .forms import Itemform


def index(request):
    """For showing the index(main) page consisting of all the lists."""
    todolists = TodoList.objects.all()
    template = loader.get_template('todo_list/index.html')
    context = {
        'todolists': todolists,
    }
    return render(request, 'todo_list/index.html', context)


def details(request, list_id):
    """For showing the details page consisting of all the items of a list."""
    try:
        todolist = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        raise Http404("This List Does not Exists")
    items_list = TodoItem.objects.filter(todo_list=todolist)
    template = loader.get_template('todo_list/details.html')
    context = {
        'todolist': todolist,
        'items_list': items_list
    }
    return render(request, 'todo_list/details.html', context)


def create(request):
    """Create a list."""
    template = loader.get_template('todo_list/createlist.html')
    if request.method == "GET":
        return render(request, 'todo_list/createlist.html')
    elif request.method == "POST":
        name = request.POST["name"]
        try:
            test=TodoList.objects.get(list_name=name)
        except TodoList.DoesNotExist:
            test = None
        except TodoList.MultipleObjectsReturned:
            raise Http404("This List name already exists")
        if test is None: 
            TodoList.objects.create(list_name=name)
            lists = TodoList.objects.all()
            context = {
                'todolists': lists,
            }
            return render(request, 'todo_list/index.html', context)
        else:
            raise Http404("This List name already exists")


def delete_list(request, list_id):
    """Deletes a list."""
    try:
        todolist = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        raise Http404("This List Does not Exists")
    if todolist:
        todolist.delete()
        return redirect(f'/todo_list')


def update_list(request, list_id):
    """Updates an existing list."""
    template = loader.get_template('todo_list/updatelist.html')
    try:
        todolist = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        raise Http404("This List Does not Exists")
    if request.method == "GET":
        return render(request, 'todo_list/updatelist.html')
    elif request.method == "POST":
        name = request.POST["name"]
        check = TodoList.objects.get(list_name= name)
        if not check:
            todolist.list_name = name
            todolist.save()
            lists = TodoList.objects.all()
            context = {
                'todolists': lists,
            }
            return render(request, 'todo_list/index.html', context)
        else:
            raise Http404("This List name already exists. Try another name")


def delete_item(request, item_id):
    """Deletes an item from a list."""
    try:
        todoitem = TodoItem.objects.get(id=item_id)    
    except TodoItem.DoesNotExist:
        raise Http404("This Item Does not Exists")
    if todoitem:
        listID = todoitem.todo_list.id
        todoitem.delete()
        return redirect(f'/todo_list/{listID}')
    else:
        raise Http404("This Item Does not Exists")


def add_item(request, list_id):
    """Adds an item to an existing list."""
    todolist = TodoList.objects.get(id=list_id)
    if request.method == "POST":
        form = Itemform(request.POST)
        if form.is_valid():
            object = form.save(commit=False)
            object.todo_list = todolist
            object.save()
            return redirect(f'/todo_list/{list_id}')
    form = Itemform()
    context = {
        "item_info" : form
    }
    return render(request, 'todo_list/additem.html', context)


def mark_item(request, item_id):
    """To mark an item(task) as done."""
    try:
        todoitem = TodoItem.objects.get(id=item_id)
    except TodoList.DoesNotExist:
        raise Http404("This Item Does not Exists")
    listID = todoitem.todo_list.id
    todoitem.checked = True
    todoitem.save()
    return redirect(f'/todo_list/{listID}')


def update_item(request, item_id):
    """Updates an already existing item(task)."""
    form = Itemform()
    try:
        todoitem = TodoItem.objects.get(id=item_id)
        
    except TodoItem.DoesNotExist:
        raise Http404("This Item Does not Exists")
    list_id = todoitem.todo_list.id
    form = Itemform(request.POST or None, instance=todoitem)
    if form.is_valid():
        form.save()
        return redirect(f'/todo_list/{list_id}')
    
    context = {
        "update_info" : form
    }
    return render(request, 'todo_list/updateitem.html', context)


    
    
    
    
    


 


    

    

todo_list/templates/todo_list/additem.html
<h1>TODO LIST</h1>
<hr>
<form  method="post">
    {% csrf_token %}
    {{item_info.as_p}}
    <input type="submit">
</form>  
{% comment %} <h1>TODO LIST</h1>
<form  action="{% url 'todo:item_add' todolist.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>Add item</h1>
        <label>Title:</label><br>
        <input type="text" name="task" id="task" required><br><br>
        <label>Checked:</label>
        <input type="checkbox" name="check" id="check" value="1"><br><br> 

        <label>Due date:</label><br>
        <input type="datetime-local" name="due" id="due" required><br><br> 

        <input type="submit">
    </fieldset>

</form> {% endcomment %}

todo_list/templates/todo_list/createlist.html
<h1>TODO LIST</h1>
<hr>
<form action="{% url 'todo:list_create' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>Create New List</h1>
        <label>List name:</label><br>
        <input type="text" name="name" id="name" required><br><br>
        {% comment %} <label>Title:</label><br>
        <input type="text" name="task" id="task" required><br><br>
        <label>Due date:</label><br>
        <input type="date" name="due" id="due" required><br><br> {% endcomment %}

        <input type="submit">
    </fieldset>

</form>

todo_list/templates/todo_list/details.html
<h1>TODO LIST</h1>
<hr>
<h1>{{todolist.list_name}}</h1>
<button><span><a href="/todo_list/addI/{{todolist.id}}" style = 'text-decoration: none;'>Add item</a></span></button>
<h3>Tasks pending</h3>
<ul>
    {% for item in items_list %}
    {%if not item.checked %}
        <li>
            {{item.title}}: {{item.due_date}}, {{item.checked}}
            <br>
            <button><span><a href="/todo_list/deleteI/{{item.id}}" style = 'text-decoration: none;'>Delete</a></span></button>
            <button><span><a href="/todo_list/markI/{{item.id}}" style = 'text-decoration: none;'>Mark as done</a></span></button>
            <button><span><a href="/todo_list/updateI/{{item.id}}" style = 'text-decoration: none;'>Edit</a></span></button>

        </li>
    {%endif%}
    
    {% endfor %}
</ul>
<hr>
<h3>Tasks done</h3>
<ul>
    {% for item in items_list %}
    {%if item.checked %}
        <li>
            {{item.title}}: {{item.due_date}}, {{item.checked}}
            <br>
            <button><span><a href="/todo_list/deleteI/{{item.id}}" style = 'text-decoration: none;'>Delete</a></span></button>
        </li>
    {%endif%}
    
    {% endfor %}
</ul>

todo_list/templates/todo_list/index.html
<h1>TODO LIST</h1>
<hr>
<button name="button"><a href="/todo_list/create">Create new list</a></button>
{% if todolists %}

    <ul>
        {% for todolist in todolists %}
        <li><a href="/todo_list/{{todolist.id}}">{{todolist.list_name}}</a></li>
        <button><span><a href="/todo_list/deleteL/{{todolist.id}}" style = 'text-decoration: none;'>Delete</a></span></button>
        <button><span><a href="{% url 'todo:list_update' todolist.id %}" style = 'text-decoration: none;'>Update list</a></span></button>
        {% endfor %}
    </ul>

{% endif %}

todo_list/templates/todo_list/updateitem.html
<h1>TODO LIST</h1>
<hr>
<form  method="post">
    {% csrf_token %}
    {{update_info.as_p}}
    <input type="submit">
</form>

todo_list/templates/todo_list/updatelist.html
<h1>TODO LIST</h1>
<hr>
<form  method="post">
    {% csrf_token %}
    <fieldset>
        <h1>Update this list</h1>
        <label>New List name:</label><br>
        <input type="text" name="name" id="name" required><br><br>
        <input type="submit">
    </fieldset>

</form>